apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::336468392098:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-QzGth0TODvXW
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::336468392098:user/naresh
      username: naresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::160885265516:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-08T06:50:16Z"
  name: aws-auth
  resourceVersion: "1218"
  uid: 2c5898da-f687-40a7-8a48-7997d70683c6
